before_install:
- openssl aes-256-cbc -K $encrypted_87a7346dce65_key -iv $encrypted_87a7346dce65_iv -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar

language: python
python: "3.6"
install:
  pip install -r requirements.txt
script:
  pytest
