before_install:
- openssl aes-256-cbc -K $encrypted_87a7346dce65_key -iv $encrypted_87a7346dce65_iv -in secret.tar.enc -out secret.tar -d

language: python
python: "3.6"
install:
  pip install -r requirements
script:
  pytest
